Update patch set 3
Patch Set 3:

Applying this patch fails with:
Applying change number 285834...
--> Subject:       "DO NOT MERGE - Only autoVerify at install for new hosts"
--> Project path:  frameworks/base
--> Change number: 285834 (Patch Set 3)
['git fetch github', u'refs/changes/34/285834/3']
From git://github.com/LineageOS/android_frameworks_base
 * branch                    refs/changes/34/285834/3 -> FETCH_HEAD
Auto-merging services/core/java/com/android/server/pm/Settings.java
CONFLICT (content): Merge conflict in services/core/java/com/android/server/pm/Settings.java
Auto-merging services/core/java/com/android/server/pm/PackageManagerService.java
CONFLICT (content): Merge conflict in services/core/java/com/android/server/pm/PackageManagerService.java
error: could not apply 3afe56629d4... DO NOT MERGE - Only autoVerify at install for new hosts
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Recorded preimage for 'services/core/java/com/android/server/pm/PackageManagerService.java'
Recorded preimage for 'services/core/java/com/android/server/pm/Settings.java'
ERROR: git command failed

Patch-set: 3
CC: Gerrit User 26658 <26658@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>