Update patch set 2
Patch Set 2: Verified-1 Code-Review-1

packageInfo used outside try block.

frameworks/base/core/java/android/webkit/WebViewFactory.java:222: error: package
 packageInfo does not exist
        if (packageInfo.applicationInfo.primaryCpuAbi == null) {
                       ^
frameworks/base/core/java/android/webkit/WebViewFactory.java:226: error: cannot 
find symbol
        sPackageInfo = packageInfo;
                       ^
  symbol:   variable packageInfo
  location: class WebViewFactory
2 errors

Patch-set: 2
Reviewer: Gerrit User 6360 <6360@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=-1
Label: Code-Review=-1