Lockscreen: Introduce window type TYPE_KEYGUARD_PANEL
This window type will be used by third party keyguard components
so that they can be layered within the keyguard while running in
their own process.  This window type will use the same Z ordering
as TYPE_STATUS_BAR_SUB_PANEL, which is currently unused.

Note from SHM:
 * This also fixes the following errors while compiling for the emulator:

ERROR: vendor/cmsdk/tests/src/org/cyanogenmod/tests/externalviews/keyguardexternalviews/KeyguardExternalProviderTest.java:199: TYPE_KEYGUARD_PANEL cannot be resolved or is not a field
ERROR: vendor/cmsdk/tests/src/org/cyanogenmod/tests/externalviews/keyguardexternalviews/KeyguardExternalProviderTest.java:200: TYPE_KEYGUARD_PANEL cannot be resolved or is not a field

Change-Id: Ie18caf12a55ba79a5c56a36ca79b3a6e377d7529