Update patch set 1
Patch Set 1:

Which topic, oreo-lights or oreo-mr1-buttons-redux?

@Sam, I tried to move configs to the SDK, but I failed badly: 

> frameworks/base/core/java/android/os/PowerManager.java:1543: error: package org.lineageos.platform.internal.R does not exist
>                org.lineageos.platform.internal.R.integer.config_buttonBrightnessSettingDefault);

Also, we need to decide if we bring back removed code to allow porting keyboard backlight support or not.

Patch-set: 1