Update patch set 2
Patch Set 2:

This breaks build.

frameworks/base/services/core/jni/com_android_server_AlarmManagerService.cpp:62:1: error: too many initializers for 'const clockid_t [6] {aka const int [6]}'

Patch-set: 2
Reviewer: Edwin Moquete <14947@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0