Revert "Bluetooth: DUT discovery the correct adapter name"
This fixes the following crash when forgetting a device:

FATAL EXCEPTION: main
Process: com.android.settings, PID: 2731
java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
    at android.os.Parcel.readException(Parcel.java:1690)
    at android.os.Parcel.readException(Parcel.java:1637)
    at android.bluetooth.IBluetooth$Stub$Proxy.setRemoteAlias(IBluetooth.java:1425)
    at android.bluetooth.BluetoothDevice.setAlias(BluetoothDevice.java:790)
    at com.android.settingslib.bluetooth.CachedBluetoothDevice.unpair(CachedBluetoothDevice.java:332)
    at com.android.settings.bluetooth.DeviceProfilesSettings.onClick(DeviceProfilesSettings.java:121)
    at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6126)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
   Force finishing activity com.android.settings/.Settings$BluetoothSettingsActivity

This reverts commit da544cc88f0213c025b6e733bd2870e3282ca380.

Change-Id: Idc8cf39e6c05123a2010cd9cef16bb99268fae25