Update patch set 7
Patch Set 7:

Whitelist entries missing, breaks building s5neolte - is this nvidia profile manager included for all devices?

 repo sync && make clobber && . build/envsetup.sh && breakfast s5neolte && mm -j && m ramdisk-nodeps && m recoveryimage-nodeps

 [  1% 14/708] Check package name for  out/target/common/obj/JAVA_LIBRARIES/core- 
oj_intermediates/classes.jar  out/target/common/obj/JAV
FAILED: out/target/common/obj/PACKAGING/boot-jars-package-check_intermediates/stamp
/bin/bash -c "(build/make/core/tasks/check_boot_jars/check_boot_jars.py build/make/core/tasks/check_boot_jars/package_whitelist.txt  out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/classes.jar  out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/classes.jar  out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/classes.jar  out/target/common/obj/JAVA_LIBRARIES/bouncycastle_intermediates/classes.jar  out/target/common/obj/JAVA_LIBRARIES/apache-xml_intermediates/classes.jar  out/target/common/obj/JAVA_LIBRARIES/conscrypt_intermediates/classes.jar  out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes.jar  out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/classes.jar  out/target/common/obj/JAVA_LIBRARIES/telephony-common_intermediates/classes.jar  out/target/common/obj/JAVA_LIBRARIES/voip-common_intermediates/classes.jar  out/target/common/obj/JAVA_LIBRARIES/ims-common_intermediates/classes.jar  out/target/common/obj/JAVA_LIBRARIES/updatable-media_intermediates/classes.jar  out/target/common/obj/JAVA_LIBRARIES/android.test.base_intermediates/classes.jar ) && (mkdir -p out/target/common/obj/PACKAGING/boot-jars-package-check_intermediates/ && touch out/target/common/obj/PACKAGING/boot-jars-package-check_intermediates/stamp )"
Error: out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes.jar contains class file com/nvidia/profilemanager/ProfileTypeId.class, whose package name com.nvidia.profilemanager is not in the whitelist build/make/core/tasks/check_boot_jars/package_whitelist.txt of packages allowed on the bootclasspath.
[  2% 19/708] Building Kernel Image (Image)

Reverting c7c48b0 fixed it for me.

Patch-set: 7
CC: Gerrit User 27868 <27868@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>