Update patch set 1
Patch Set 1:

> ERROR: /frameworks/base/core/java/android/os/Build.java:715: The
 > method isApplicationUid(int) is undefined for the type Process
 > 
 > Suggestions?

Ah fuck...quite honestly this particular problem is a bit out of my realm because this method is actually part of a commit in N that adds some new api methods. https://github.com/CyanogenMod/android_frameworks_base/commit/48aa86bd0b30815f4c02561f713bd33b032ef2b7

I'm hoping Danny will weigh in here, but I'm wondering if we can get by without the UID check.

Otherwise revert I guess...

Patch-set: 1