TextLine: Prevent OOB reads in measure()
The commit I7089ed9b711dddd7de2b27c9c2fa0fb4cb53a735
("RESTRICT AUTOMERGE Do not compute outside given range in TextLine")
removed the runLimit saturation and introduced the OOB read:

--------- beginning of crash
FATAL EXCEPTION: main
Process: com.linkedin.android, PID: 4144
java.lang.ArrayIndexOutOfBoundsException: length=114; index=114
          at android.text.TextLine.measure(TextLine.java:294)
          at android.text.TextLine.metrics(TextLine.java:249)
          at android.text.Layout.getLineExtent(Layout.java:1185)
          at android.text.Layout.getLineWidth(Layout.java:1151)

This commit restores back the limitation after the security check
has passed.

Change-Id: I40c2c03a97d5c972212fc4d3c3684b77f1596834
Signed-off-by: Vasyl Gello <vasek.gello@gmail.com>