Fix: "Camera: Simplify code for Aux/Mono white and black lists".
  Without importing java.util.Arrays 241215 breaks the build with:

frameworks/base/core/java/android/hardware/Camera.java:302: error: cannot find symbol
            if (Arrays.asList(packageList.split(",")).contains(packageName)) {
                ^
  symbol:   variable Arrays
  location: class Camera
frameworks/base/core/java/android/hardware/Camera.java:307: error: cannot find symbol
            if (Arrays.asList(packageBlacklist.split(",")).contains(packageName)) {
                ^
  symbol:   variable Arrays
  location: class Camera
2 errors

Change-Id: I1fef3ea2472e8b92412afbab7ca36f5648e1a4ec